
// This file has been generated by the GUI designer. Do not modify.
namespace LRDemo
{
	public partial class HistoryWidget
	{
		private global::Gtk.Table tblLayout;
		private global::Gtk.Table tblBalanceRequest;
		private global::Gtk.Frame operationParamsFrame;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Table tblBalanceOperation;
		private global::Gtk.ComboBox cmbAnonymous;
		private global::Gtk.ComboBox cmbCurrency;
		private global::Gtk.ComboBox cmbDirection;
		private global::Gtk.Label lblAccountNumber;
		private global::Gtk.Label lblAnonymity;
		private global::Gtk.Label lblCorrespondingAccountId;
		private global::Gtk.Label lblCurrency;
		private global::Gtk.Label lblDirection;
		private global::Gtk.Label lblEndAmount;
		private global::Gtk.Label lblEndDate;
		private global::Gtk.Label lblPageNumber;
		private global::Gtk.Label lblPageSize;
		private global::Gtk.Label lblReceiptId;
		private global::Gtk.Label lblSource;
		private global::Gtk.Label lblStartAmount;
		private global::Gtk.Label lblStartDate;
		private global::Gtk.Label lblTransferId;
		private global::Gtk.HButtonBox sendHBox;
		private global::Gtk.Button btnSend;
		private global::Gtk.Entry txtAccountNumber;
		private global::Gtk.Entry txtCorrespondingAcount;
		private global::Gtk.SpinButton txtEndAmount;
		private global::Gtk.Entry txtEndDate;
		private global::Gtk.SpinButton txtPageNumber;
		private global::Gtk.SpinButton txtPageSize;
		private global::Gtk.Entry txtReceiptId;
		private global::Gtk.Entry txtSource;
		private global::Gtk.SpinButton txtStartAmount;
		private global::Gtk.Entry txtStartDate;
		private global::Gtk.Entry txtTransferId;
		private global::Gtk.Label operationParameters;
		private global::Gtk.Table tblResponse;
		private global::Gtk.Frame balanceFrame;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.NodeView historyNodeView;
		private global::Gtk.Label lblHistory;
		private global::Gtk.Frame rawResponseFrame;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView txtRawResponse;
		private global::Gtk.Label lblRowResponse;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LRDemo.HistoryWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LRDemo.HistoryWidget";
			// Container child LRDemo.HistoryWidget.Gtk.Container+ContainerChild
			this.tblLayout = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.tblLayout.Name = "tblLayout";
			this.tblLayout.RowSpacing = ((uint)(6));
			this.tblLayout.ColumnSpacing = ((uint)(6));
			// Container child tblLayout.Gtk.Table+TableChild
			this.tblBalanceRequest = new global::Gtk.Table (((uint)(1)), ((uint)(1)), false);
			this.tblBalanceRequest.Name = "tblBalanceRequest";
			this.tblBalanceRequest.RowSpacing = ((uint)(6));
			this.tblBalanceRequest.ColumnSpacing = ((uint)(6));
			// Container child tblBalanceRequest.Gtk.Table+TableChild
			this.operationParamsFrame = new global::Gtk.Frame ();
			this.operationParamsFrame.Name = "operationParamsFrame";
			this.operationParamsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child operationParamsFrame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.tblBalanceOperation = new global::Gtk.Table (((uint)(8)), ((uint)(4)), false);
			this.tblBalanceOperation.Name = "tblBalanceOperation";
			this.tblBalanceOperation.RowSpacing = ((uint)(6));
			this.tblBalanceOperation.ColumnSpacing = ((uint)(6));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.cmbAnonymous = global::Gtk.ComboBox.NewText ();
			this.cmbAnonymous.Name = "cmbAnonymous";
			this.tblBalanceOperation.Add (this.cmbAnonymous);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.cmbAnonymous]));
			w1.TopAttach = ((uint)(5));
			w1.BottomAttach = ((uint)(6));
			w1.LeftAttach = ((uint)(3));
			w1.RightAttach = ((uint)(4));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.cmbCurrency = global::Gtk.ComboBox.NewText ();
			this.cmbCurrency.Name = "cmbCurrency";
			this.cmbCurrency.HasFrame = false;
			this.tblBalanceOperation.Add (this.cmbCurrency);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.cmbCurrency]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.cmbDirection = global::Gtk.ComboBox.NewText ();
			this.cmbDirection.Name = "cmbDirection";
			this.tblBalanceOperation.Add (this.cmbDirection);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.cmbDirection]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(3));
			w3.RightAttach = ((uint)(4));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblAccountNumber = new global::Gtk.Label ();
			this.lblAccountNumber.Name = "lblAccountNumber";
			this.lblAccountNumber.Xalign = 1F;
			this.lblAccountNumber.LabelProp = global::Mono.Unix.Catalog.GetString ("Account ID:");
			this.tblBalanceOperation.Add (this.lblAccountNumber);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblAccountNumber]));
			w4.YPadding = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblAnonymity = new global::Gtk.Label ();
			this.lblAnonymity.Name = "lblAnonymity";
			this.lblAnonymity.Xalign = 1F;
			this.lblAnonymity.LabelProp = global::Mono.Unix.Catalog.GetString ("Anonymous:");
			this.tblBalanceOperation.Add (this.lblAnonymity);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblAnonymity]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblCorrespondingAccountId = new global::Gtk.Label ();
			this.lblCorrespondingAccountId.Name = "lblCorrespondingAccountId";
			this.lblCorrespondingAccountId.Xalign = 1F;
			this.lblCorrespondingAccountId.LabelProp = global::Mono.Unix.Catalog.GetString ("Corresponding Account ID:");
			this.tblBalanceOperation.Add (this.lblCorrespondingAccountId);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblCorrespondingAccountId]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblCurrency = new global::Gtk.Label ();
			this.lblCurrency.Name = "lblCurrency";
			this.lblCurrency.Xalign = 1F;
			this.lblCurrency.LabelProp = global::Mono.Unix.Catalog.GetString ("Currency:");
			this.tblBalanceOperation.Add (this.lblCurrency);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblCurrency]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblDirection = new global::Gtk.Label ();
			this.lblDirection.Name = "lblDirection";
			this.lblDirection.Xalign = 1F;
			this.lblDirection.LabelProp = global::Mono.Unix.Catalog.GetString ("Direction:");
			this.tblBalanceOperation.Add (this.lblDirection);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblDirection]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblEndAmount = new global::Gtk.Label ();
			this.lblEndAmount.Name = "lblEndAmount";
			this.lblEndAmount.Xalign = 1F;
			this.lblEndAmount.LabelProp = global::Mono.Unix.Catalog.GetString ("End Amount:");
			this.tblBalanceOperation.Add (this.lblEndAmount);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblEndAmount]));
			w9.TopAttach = ((uint)(5));
			w9.BottomAttach = ((uint)(6));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblEndDate = new global::Gtk.Label ();
			this.lblEndDate.Name = "lblEndDate";
			this.lblEndDate.Xalign = 1F;
			this.lblEndDate.LabelProp = global::Mono.Unix.Catalog.GetString ("End Date:");
			this.tblBalanceOperation.Add (this.lblEndDate);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblEndDate]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblPageNumber = new global::Gtk.Label ();
			this.lblPageNumber.Name = "lblPageNumber";
			this.lblPageNumber.Xalign = 1F;
			this.lblPageNumber.LabelProp = global::Mono.Unix.Catalog.GetString ("Page Number:");
			this.tblBalanceOperation.Add (this.lblPageNumber);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblPageNumber]));
			w11.TopAttach = ((uint)(6));
			w11.BottomAttach = ((uint)(7));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblPageSize = new global::Gtk.Label ();
			this.lblPageSize.Name = "lblPageSize";
			this.lblPageSize.Xalign = 1F;
			this.lblPageSize.LabelProp = global::Mono.Unix.Catalog.GetString ("Page Size:");
			this.tblBalanceOperation.Add (this.lblPageSize);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblPageSize]));
			w12.TopAttach = ((uint)(6));
			w12.BottomAttach = ((uint)(7));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblReceiptId = new global::Gtk.Label ();
			this.lblReceiptId.Name = "lblReceiptId";
			this.lblReceiptId.Xalign = 1F;
			this.lblReceiptId.LabelProp = global::Mono.Unix.Catalog.GetString ("Receipt ID:");
			this.tblBalanceOperation.Add (this.lblReceiptId);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblReceiptId]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblSource = new global::Gtk.Label ();
			this.lblSource.Name = "lblSource";
			this.lblSource.Xalign = 1F;
			this.lblSource.LabelProp = global::Mono.Unix.Catalog.GetString ("Source:");
			this.tblBalanceOperation.Add (this.lblSource);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblSource]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.LeftAttach = ((uint)(2));
			w14.RightAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblStartAmount = new global::Gtk.Label ();
			this.lblStartAmount.Name = "lblStartAmount";
			this.lblStartAmount.Xalign = 1F;
			this.lblStartAmount.LabelProp = global::Mono.Unix.Catalog.GetString ("Start Amount:");
			this.tblBalanceOperation.Add (this.lblStartAmount);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblStartAmount]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblStartDate = new global::Gtk.Label ();
			this.lblStartDate.Name = "lblStartDate";
			this.lblStartDate.Xalign = 1F;
			this.lblStartDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Start Date:");
			this.tblBalanceOperation.Add (this.lblStartDate);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblStartDate]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblTransferId = new global::Gtk.Label ();
			this.lblTransferId.Name = "lblTransferId";
			this.lblTransferId.Xalign = 1F;
			this.lblTransferId.LabelProp = global::Mono.Unix.Catalog.GetString ("Transfer ID:");
			this.tblBalanceOperation.Add (this.lblTransferId);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblTransferId]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.sendHBox = new global::Gtk.HButtonBox ();
			this.sendHBox.Name = "sendHBox";
			this.sendHBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child sendHBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnSend = new global::Gtk.Button ();
			this.btnSend.CanFocus = true;
			this.btnSend.Name = "btnSend";
			this.btnSend.UseUnderline = true;
			this.btnSend.Label = global::Mono.Unix.Catalog.GetString ("Send");
			this.sendHBox.Add (this.btnSend);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.sendHBox [this.btnSend]));
			w18.Expand = false;
			w18.Fill = false;
			this.tblBalanceOperation.Add (this.sendHBox);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.sendHBox]));
			w19.TopAttach = ((uint)(7));
			w19.BottomAttach = ((uint)(8));
			w19.LeftAttach = ((uint)(3));
			w19.RightAttach = ((uint)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtAccountNumber = new global::Gtk.Entry ();
			this.txtAccountNumber.CanFocus = true;
			this.txtAccountNumber.Name = "txtAccountNumber";
			this.txtAccountNumber.IsEditable = true;
			this.txtAccountNumber.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtAccountNumber);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtAccountNumber]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YPadding = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtCorrespondingAcount = new global::Gtk.Entry ();
			this.txtCorrespondingAcount.CanFocus = true;
			this.txtCorrespondingAcount.Name = "txtCorrespondingAcount";
			this.txtCorrespondingAcount.IsEditable = true;
			this.txtCorrespondingAcount.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtCorrespondingAcount);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtCorrespondingAcount]));
			w21.LeftAttach = ((uint)(3));
			w21.RightAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtEndAmount = new global::Gtk.SpinButton (0, 100000, 1);
			this.txtEndAmount.CanFocus = true;
			this.txtEndAmount.Name = "txtEndAmount";
			this.txtEndAmount.Adjustment.PageIncrement = 10;
			this.txtEndAmount.ClimbRate = 1;
			this.txtEndAmount.Digits = ((uint)(4));
			this.txtEndAmount.Numeric = true;
			this.tblBalanceOperation.Add (this.txtEndAmount);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtEndAmount]));
			w22.TopAttach = ((uint)(5));
			w22.BottomAttach = ((uint)(6));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtEndDate = new global::Gtk.Entry ();
			this.txtEndDate.CanFocus = true;
			this.txtEndDate.Name = "txtEndDate";
			this.txtEndDate.IsEditable = true;
			this.txtEndDate.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtEndDate);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtEndDate]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtPageNumber = new global::Gtk.SpinButton (0, 1000, 1);
			this.txtPageNumber.CanFocus = true;
			this.txtPageNumber.Name = "txtPageNumber";
			this.txtPageNumber.Adjustment.PageIncrement = 10;
			this.txtPageNumber.ClimbRate = 1;
			this.txtPageNumber.Numeric = true;
			this.tblBalanceOperation.Add (this.txtPageNumber);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtPageNumber]));
			w24.TopAttach = ((uint)(6));
			w24.BottomAttach = ((uint)(7));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtPageSize = new global::Gtk.SpinButton (0, 20, 1);
			this.txtPageSize.CanFocus = true;
			this.txtPageSize.Name = "txtPageSize";
			this.txtPageSize.Adjustment.PageIncrement = 10;
			this.txtPageSize.ClimbRate = 1;
			this.txtPageSize.Numeric = true;
			this.tblBalanceOperation.Add (this.txtPageSize);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtPageSize]));
			w25.TopAttach = ((uint)(6));
			w25.BottomAttach = ((uint)(7));
			w25.LeftAttach = ((uint)(3));
			w25.RightAttach = ((uint)(4));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtReceiptId = new global::Gtk.Entry ();
			this.txtReceiptId.CanFocus = true;
			this.txtReceiptId.Name = "txtReceiptId";
			this.txtReceiptId.IsEditable = true;
			this.txtReceiptId.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtReceiptId);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtReceiptId]));
			w26.TopAttach = ((uint)(3));
			w26.BottomAttach = ((uint)(4));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtSource = new global::Gtk.Entry ();
			this.txtSource.CanFocus = true;
			this.txtSource.Name = "txtSource";
			this.txtSource.IsEditable = true;
			this.txtSource.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtSource);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtSource]));
			w27.TopAttach = ((uint)(4));
			w27.BottomAttach = ((uint)(5));
			w27.LeftAttach = ((uint)(3));
			w27.RightAttach = ((uint)(4));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtStartAmount = new global::Gtk.SpinButton (0, 100000, 1);
			this.txtStartAmount.CanFocus = true;
			this.txtStartAmount.Name = "txtStartAmount";
			this.txtStartAmount.Adjustment.PageIncrement = 10;
			this.txtStartAmount.ClimbRate = 1;
			this.txtStartAmount.Digits = ((uint)(4));
			this.txtStartAmount.Numeric = true;
			this.tblBalanceOperation.Add (this.txtStartAmount);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtStartAmount]));
			w28.TopAttach = ((uint)(4));
			w28.BottomAttach = ((uint)(5));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtStartDate = new global::Gtk.Entry ();
			this.txtStartDate.CanFocus = true;
			this.txtStartDate.Name = "txtStartDate";
			this.txtStartDate.IsEditable = true;
			this.txtStartDate.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtStartDate);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtStartDate]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtTransferId = new global::Gtk.Entry ();
			this.txtTransferId.CanFocus = true;
			this.txtTransferId.Name = "txtTransferId";
			this.txtTransferId.IsEditable = true;
			this.txtTransferId.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtTransferId);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtTransferId]));
			w30.TopAttach = ((uint)(2));
			w30.BottomAttach = ((uint)(3));
			w30.LeftAttach = ((uint)(3));
			w30.RightAttach = ((uint)(4));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.tblBalanceOperation);
			this.operationParamsFrame.Add (this.GtkAlignment);
			this.operationParameters = new global::Gtk.Label ();
			this.operationParameters.Name = "operationParameters";
			this.operationParameters.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Operation Parameters</b>");
			this.operationParameters.UseMarkup = true;
			this.operationParamsFrame.LabelWidget = this.operationParameters;
			this.tblBalanceRequest.Add (this.operationParamsFrame);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.tblBalanceRequest [this.operationParamsFrame]));
			w33.XPadding = ((uint)(3));
			w33.YPadding = ((uint)(3));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			this.tblLayout.Add (this.tblBalanceRequest);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.tblLayout [this.tblBalanceRequest]));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblLayout.Gtk.Table+TableChild
			this.tblResponse = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tblResponse.Name = "tblResponse";
			this.tblResponse.RowSpacing = ((uint)(6));
			this.tblResponse.ColumnSpacing = ((uint)(6));
			// Container child tblResponse.Gtk.Table+TableChild
			this.balanceFrame = new global::Gtk.Frame ();
			this.balanceFrame.Name = "balanceFrame";
			this.balanceFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child balanceFrame.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.historyNodeView = new global::Gtk.NodeView ();
			this.historyNodeView.CanFocus = true;
			this.historyNodeView.Name = "historyNodeView";
			this.GtkScrolledWindow2.Add (this.historyNodeView);
			this.GtkAlignment3.Add (this.GtkScrolledWindow2);
			this.balanceFrame.Add (this.GtkAlignment3);
			this.lblHistory = new global::Gtk.Label ();
			this.lblHistory.Name = "lblHistory";
			this.lblHistory.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>History</b>");
			this.lblHistory.UseMarkup = true;
			this.balanceFrame.LabelWidget = this.lblHistory;
			this.tblResponse.Add (this.balanceFrame);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.tblResponse [this.balanceFrame]));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			// Container child tblResponse.Gtk.Table+TableChild
			this.rawResponseFrame = new global::Gtk.Frame ();
			this.rawResponseFrame.Name = "rawResponseFrame";
			this.rawResponseFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child rawResponseFrame.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtRawResponse = new global::Gtk.TextView ();
			this.txtRawResponse.CanFocus = true;
			this.txtRawResponse.Name = "txtRawResponse";
			this.txtRawResponse.Editable = false;
			this.txtRawResponse.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add (this.txtRawResponse);
			this.GtkAlignment2.Add (this.GtkScrolledWindow1);
			this.rawResponseFrame.Add (this.GtkAlignment2);
			this.lblRowResponse = new global::Gtk.Label ();
			this.lblRowResponse.Name = "lblRowResponse";
			this.lblRowResponse.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Raw Response</b>");
			this.lblRowResponse.UseMarkup = true;
			this.rawResponseFrame.LabelWidget = this.lblRowResponse;
			this.tblResponse.Add (this.rawResponseFrame);
			this.tblLayout.Add (this.tblResponse);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.tblLayout [this.tblResponse]));
			w43.TopAttach = ((uint)(1));
			w43.BottomAttach = ((uint)(2));
			this.Add (this.tblLayout);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnSend.Clicked += new global::System.EventHandler (this.OnSendRequestClicked);
		}
	}
}
