
// This file has been generated by the GUI designer. Do not modify.
namespace LRDemo
{
	public partial class TransferWidget
	{
		private global::Gtk.Table tblLayout;
		private global::Gtk.Table tblBalanceRequest;
		private global::Gtk.Frame operationParamsFrame;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Table tblBalanceOperation;
		private global::Gtk.CheckButton chkAnonymous;
		private global::Gtk.ComboBox cmbCurrency;
		private global::Gtk.VBox descriptionVBox;
		private global::Gtk.Label lblDescription;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TextView txtDescription;
		private global::Gtk.Label lblAmount;
		private global::Gtk.Label lblAnonymous;
		private global::Gtk.Label lblCurrency;
		private global::Gtk.Label lblPayee;
		private global::Gtk.Label lblPayer;
		private global::Gtk.Label lblTransferId;
		private global::Gtk.Entry txtAmount;
		private global::Gtk.Entry txtPayee;
		private global::Gtk.Entry txtPayer;
		private global::Gtk.Entry txtTransferId;
		private global::Gtk.Label operationParameters;
		private global::Gtk.VButtonBox pnlOperationButtons;
		private global::Gtk.Button btnAddOperation;
		private global::Gtk.Button btnRemoveOperation;
		private global::Gtk.Button btnSendRequest;
		private global::Gtk.Frame requestOperationsFrame;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView operationsNodeView;
		private global::Gtk.Label lblRequestOperations;
		private global::Gtk.Table tblResponse;
		private global::Gtk.Frame balanceFrame;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.NodeView receiptNodeView;
		private global::Gtk.Label lblReceipt;
		private global::Gtk.Frame rawResponseFrame;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView txtRawResponse;
		private global::Gtk.Label lblRowResponse;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LRDemo.TransferWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LRDemo.TransferWidget";
			// Container child LRDemo.TransferWidget.Gtk.Container+ContainerChild
			this.tblLayout = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.tblLayout.Name = "tblLayout";
			this.tblLayout.RowSpacing = ((uint)(6));
			this.tblLayout.ColumnSpacing = ((uint)(6));
			// Container child tblLayout.Gtk.Table+TableChild
			this.tblBalanceRequest = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.tblBalanceRequest.Name = "tblBalanceRequest";
			this.tblBalanceRequest.RowSpacing = ((uint)(6));
			this.tblBalanceRequest.ColumnSpacing = ((uint)(6));
			// Container child tblBalanceRequest.Gtk.Table+TableChild
			this.operationParamsFrame = new global::Gtk.Frame ();
			this.operationParamsFrame.Name = "operationParamsFrame";
			this.operationParamsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child operationParamsFrame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.tblBalanceOperation = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.tblBalanceOperation.Name = "tblBalanceOperation";
			this.tblBalanceOperation.RowSpacing = ((uint)(6));
			this.tblBalanceOperation.ColumnSpacing = ((uint)(6));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.chkAnonymous = new global::Gtk.CheckButton ();
			this.chkAnonymous.CanFocus = true;
			this.chkAnonymous.Name = "chkAnonymous";
			this.chkAnonymous.Label = "";
			this.chkAnonymous.DrawIndicator = true;
			this.chkAnonymous.UseUnderline = true;
			this.tblBalanceOperation.Add (this.chkAnonymous);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.chkAnonymous]));
			w1.TopAttach = ((uint)(5));
			w1.BottomAttach = ((uint)(6));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.cmbCurrency = global::Gtk.ComboBox.NewText ();
			this.cmbCurrency.Name = "cmbCurrency";
			this.cmbCurrency.HasFrame = false;
			this.tblBalanceOperation.Add (this.cmbCurrency);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.cmbCurrency]));
			w2.TopAttach = ((uint)(3));
			w2.BottomAttach = ((uint)(4));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.descriptionVBox = new global::Gtk.VBox ();
			this.descriptionVBox.Name = "descriptionVBox";
			this.descriptionVBox.Spacing = 6;
			// Container child descriptionVBox.Gtk.Box+BoxChild
			this.lblDescription = new global::Gtk.Label ();
			this.lblDescription.Name = "lblDescription";
			this.lblDescription.Xalign = 1F;
			this.lblDescription.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
			this.descriptionVBox.Add (this.lblDescription);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.descriptionVBox [this.lblDescription]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.tblBalanceOperation.Add (this.descriptionVBox);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.descriptionVBox]));
			w4.TopAttach = ((uint)(6));
			w4.BottomAttach = ((uint)(7));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.txtDescription = new global::Gtk.TextView ();
			this.txtDescription.CanFocus = true;
			this.txtDescription.Name = "txtDescription";
			this.GtkScrolledWindow3.Add (this.txtDescription);
			this.tblBalanceOperation.Add (this.GtkScrolledWindow3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.GtkScrolledWindow3]));
			w6.TopAttach = ((uint)(6));
			w6.BottomAttach = ((uint)(7));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblAmount = new global::Gtk.Label ();
			this.lblAmount.Name = "lblAmount";
			this.lblAmount.Xalign = 1F;
			this.lblAmount.LabelProp = global::Mono.Unix.Catalog.GetString ("Amount:");
			this.tblBalanceOperation.Add (this.lblAmount);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblAmount]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblAnonymous = new global::Gtk.Label ();
			this.lblAnonymous.Name = "lblAnonymous";
			this.lblAnonymous.LabelProp = global::Mono.Unix.Catalog.GetString ("Anonymous:");
			this.tblBalanceOperation.Add (this.lblAnonymous);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblAnonymous]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblCurrency = new global::Gtk.Label ();
			this.lblCurrency.Name = "lblCurrency";
			this.lblCurrency.Xalign = 1F;
			this.lblCurrency.LabelProp = global::Mono.Unix.Catalog.GetString ("Currency:");
			this.tblBalanceOperation.Add (this.lblCurrency);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblCurrency]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblPayee = new global::Gtk.Label ();
			this.lblPayee.Name = "lblPayee";
			this.lblPayee.Xalign = 1F;
			this.lblPayee.LabelProp = global::Mono.Unix.Catalog.GetString ("Payee:");
			this.tblBalanceOperation.Add (this.lblPayee);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblPayee]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblPayer = new global::Gtk.Label ();
			this.lblPayer.Name = "lblPayer";
			this.lblPayer.Xalign = 1F;
			this.lblPayer.LabelProp = global::Mono.Unix.Catalog.GetString ("Payer:");
			this.tblBalanceOperation.Add (this.lblPayer);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblPayer]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.lblTransferId = new global::Gtk.Label ();
			this.lblTransferId.Name = "lblTransferId";
			this.lblTransferId.Xalign = 1F;
			this.lblTransferId.LabelProp = global::Mono.Unix.Catalog.GetString ("Transfer Id:");
			this.tblBalanceOperation.Add (this.lblTransferId);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.lblTransferId]));
			w12.YPadding = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtAmount = new global::Gtk.Entry ();
			this.txtAmount.CanFocus = true;
			this.txtAmount.Name = "txtAmount";
			this.txtAmount.IsEditable = true;
			this.txtAmount.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtAmount);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtAmount]));
			w13.TopAttach = ((uint)(4));
			w13.BottomAttach = ((uint)(5));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtPayee = new global::Gtk.Entry ();
			this.txtPayee.CanFocus = true;
			this.txtPayee.Name = "txtPayee";
			this.txtPayee.IsEditable = true;
			this.txtPayee.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtPayee);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtPayee]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtPayer = new global::Gtk.Entry ();
			this.txtPayer.CanFocus = true;
			this.txtPayer.Name = "txtPayer";
			this.txtPayer.IsEditable = true;
			this.txtPayer.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtPayer);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtPayer]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceOperation.Gtk.Table+TableChild
			this.txtTransferId = new global::Gtk.Entry ();
			this.txtTransferId.CanFocus = true;
			this.txtTransferId.Name = "txtTransferId";
			this.txtTransferId.IsEditable = true;
			this.txtTransferId.InvisibleChar = '●';
			this.tblBalanceOperation.Add (this.txtTransferId);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblBalanceOperation [this.txtTransferId]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.YPadding = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.tblBalanceOperation);
			this.operationParamsFrame.Add (this.GtkAlignment);
			this.operationParameters = new global::Gtk.Label ();
			this.operationParameters.Name = "operationParameters";
			this.operationParameters.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Operation Parameters</b>");
			this.operationParameters.UseMarkup = true;
			this.operationParamsFrame.LabelWidget = this.operationParameters;
			this.tblBalanceRequest.Add (this.operationParamsFrame);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblBalanceRequest [this.operationParamsFrame]));
			w19.XPadding = ((uint)(3));
			w19.YPadding = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblBalanceRequest.Gtk.Table+TableChild
			this.pnlOperationButtons = new global::Gtk.VButtonBox ();
			this.pnlOperationButtons.Name = "pnlOperationButtons";
			this.pnlOperationButtons.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child pnlOperationButtons.Gtk.ButtonBox+ButtonBoxChild
			this.btnAddOperation = new global::Gtk.Button ();
			this.btnAddOperation.CanFocus = true;
			this.btnAddOperation.Name = "btnAddOperation";
			this.btnAddOperation.UseUnderline = true;
			this.btnAddOperation.Label = global::Mono.Unix.Catalog.GetString ("Add");
			this.pnlOperationButtons.Add (this.btnAddOperation);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pnlOperationButtons [this.btnAddOperation]));
			w20.Expand = false;
			w20.Fill = false;
			// Container child pnlOperationButtons.Gtk.ButtonBox+ButtonBoxChild
			this.btnRemoveOperation = new global::Gtk.Button ();
			this.btnRemoveOperation.CanFocus = true;
			this.btnRemoveOperation.Name = "btnRemoveOperation";
			this.btnRemoveOperation.UseUnderline = true;
			this.btnRemoveOperation.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			this.pnlOperationButtons.Add (this.btnRemoveOperation);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pnlOperationButtons [this.btnRemoveOperation]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child pnlOperationButtons.Gtk.ButtonBox+ButtonBoxChild
			this.btnSendRequest = new global::Gtk.Button ();
			this.btnSendRequest.CanFocus = true;
			this.btnSendRequest.Name = "btnSendRequest";
			this.btnSendRequest.UseUnderline = true;
			this.btnSendRequest.Label = global::Mono.Unix.Catalog.GetString ("Send");
			this.pnlOperationButtons.Add (this.btnSendRequest);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pnlOperationButtons [this.btnSendRequest]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.tblBalanceRequest.Add (this.pnlOperationButtons);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblBalanceRequest [this.pnlOperationButtons]));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.YPadding = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tblBalanceRequest.Gtk.Table+TableChild
			this.requestOperationsFrame = new global::Gtk.Frame ();
			this.requestOperationsFrame.Name = "requestOperationsFrame";
			this.requestOperationsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child requestOperationsFrame.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			this.GtkAlignment1.TopPadding = ((uint)(3));
			this.GtkAlignment1.RightPadding = ((uint)(3));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.operationsNodeView = new global::Gtk.NodeView ();
			this.operationsNodeView.CanFocus = true;
			this.operationsNodeView.Name = "operationsNodeView";
			this.GtkScrolledWindow.Add (this.operationsNodeView);
			this.GtkAlignment1.Add (this.GtkScrolledWindow);
			this.requestOperationsFrame.Add (this.GtkAlignment1);
			this.lblRequestOperations = new global::Gtk.Label ();
			this.lblRequestOperations.Name = "lblRequestOperations";
			this.lblRequestOperations.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Operations In Request</b>");
			this.lblRequestOperations.UseMarkup = true;
			this.requestOperationsFrame.LabelWidget = this.lblRequestOperations;
			this.tblBalanceRequest.Add (this.requestOperationsFrame);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.tblBalanceRequest [this.requestOperationsFrame]));
			w27.LeftAttach = ((uint)(2));
			w27.RightAttach = ((uint)(3));
			w27.YPadding = ((uint)(3));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			this.tblLayout.Add (this.tblBalanceRequest);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.tblLayout [this.tblBalanceRequest]));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblLayout.Gtk.Table+TableChild
			this.tblResponse = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tblResponse.Name = "tblResponse";
			this.tblResponse.RowSpacing = ((uint)(6));
			this.tblResponse.ColumnSpacing = ((uint)(6));
			// Container child tblResponse.Gtk.Table+TableChild
			this.balanceFrame = new global::Gtk.Frame ();
			this.balanceFrame.Name = "balanceFrame";
			this.balanceFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child balanceFrame.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.receiptNodeView = new global::Gtk.NodeView ();
			this.receiptNodeView.CanFocus = true;
			this.receiptNodeView.Name = "receiptNodeView";
			this.GtkScrolledWindow2.Add (this.receiptNodeView);
			this.GtkAlignment3.Add (this.GtkScrolledWindow2);
			this.balanceFrame.Add (this.GtkAlignment3);
			this.lblReceipt = new global::Gtk.Label ();
			this.lblReceipt.Name = "lblReceipt";
			this.lblReceipt.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Receipt</b>");
			this.lblReceipt.UseMarkup = true;
			this.balanceFrame.LabelWidget = this.lblReceipt;
			this.tblResponse.Add (this.balanceFrame);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.tblResponse [this.balanceFrame]));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			// Container child tblResponse.Gtk.Table+TableChild
			this.rawResponseFrame = new global::Gtk.Frame ();
			this.rawResponseFrame.Name = "rawResponseFrame";
			this.rawResponseFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child rawResponseFrame.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtRawResponse = new global::Gtk.TextView ();
			this.txtRawResponse.CanFocus = true;
			this.txtRawResponse.Name = "txtRawResponse";
			this.txtRawResponse.Editable = false;
			this.txtRawResponse.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add (this.txtRawResponse);
			this.GtkAlignment2.Add (this.GtkScrolledWindow1);
			this.rawResponseFrame.Add (this.GtkAlignment2);
			this.lblRowResponse = new global::Gtk.Label ();
			this.lblRowResponse.Name = "lblRowResponse";
			this.lblRowResponse.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Raw Response</b>");
			this.lblRowResponse.UseMarkup = true;
			this.rawResponseFrame.LabelWidget = this.lblRowResponse;
			this.tblResponse.Add (this.rawResponseFrame);
			this.tblLayout.Add (this.tblResponse);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.tblLayout [this.tblResponse]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			this.Add (this.tblLayout);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnAddOperation.Clicked += new global::System.EventHandler (this.OnAddOperationClicked);
			this.btnRemoveOperation.Clicked += new global::System.EventHandler (this.OnRemoveOperationClicked);
			this.btnSendRequest.Clicked += new global::System.EventHandler (this.OnSendRequestClicked);
		}
	}
}
