
// This file has been generated by the GUI designer. Do not modify.
namespace LRDemo
{
	public partial class SCIPaymentRequestWidget
	{
		private global::Gtk.Table tblLayout;
		private global::Gtk.Frame paymetRequestFormFrame;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtPaymentForm;
		private global::Gtk.Label lblPaymentRequestForm;
		private global::Gtk.Frame requestParamsFrame;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.Table tblPaymentRequest;
		private global::Gtk.VBox baggageFieldsVBox;
		private global::Gtk.Label lblBaggageFields;
		private global::Gtk.ComboBox cmbCurrency;
		private global::Gtk.VBox commentsVBox;
		private global::Gtk.Label lblComments;
		private global::Gtk.HBox failUrlMethodHBox;
		private global::Gtk.RadioButton rbtFailGetMethod;
		private global::Gtk.RadioButton rbtFailPostMethod;
		private global::Gtk.RadioButton rbtFailLinkMethod;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView txtComments;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView txtBaggageFields;
		private global::Gtk.Label lblAccount;
		private global::Gtk.Label lblAmount;
		private global::Gtk.Label lblBuyerAccount;
		private global::Gtk.Label lblCurrency;
		private global::Gtk.Label lblFailUrl;
		private global::Gtk.Label lblFailUrlMethod;
		private global::Gtk.Label lblMerchantRef;
		private global::Gtk.Label lblStatusUrl;
		private global::Gtk.Label lblStatusUrlMethod;
		private global::Gtk.Label lblStore;
		private global::Gtk.Label lblSuccessUrl;
		private global::Gtk.Label lblSuccessUrlMethod;
		private global::Gtk.HButtonBox requestButtons;
		private global::Gtk.Button btnGenerate;
		private global::Gtk.HBox statusUrlMethodHBox;
		private global::Gtk.RadioButton rbtStatusGetMethod;
		private global::Gtk.RadioButton rbtStatusPostMethod;
		private global::Gtk.RadioButton rbtStatusLinkMethod;
		private global::Gtk.HBox successUrlMethodHBox;
		private global::Gtk.RadioButton rbtSuccessGetMethod;
		private global::Gtk.RadioButton rbtSuccessPostMethod;
		private global::Gtk.RadioButton rbtSuccessLinkMethod;
		private global::Gtk.SpinButton txtAmount;
		private global::Gtk.Entry txtBuyerAccount;
		private global::Gtk.Entry txtFailUrl;
		private global::Gtk.Entry txtMerchantAccount;
		private global::Gtk.Entry txtMerchantRef;
		private global::Gtk.Entry txtStatusUrl;
		private global::Gtk.Entry txtStore;
		private global::Gtk.Entry txtSuccessUrl;
		private global::Gtk.Label lblRequestParams;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LRDemo.SCIPaymentRequestWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LRDemo.SCIPaymentRequestWidget";
			// Container child LRDemo.SCIPaymentRequestWidget.Gtk.Container+ContainerChild
			this.tblLayout = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.tblLayout.Name = "tblLayout";
			this.tblLayout.RowSpacing = ((uint)(6));
			this.tblLayout.ColumnSpacing = ((uint)(6));
			// Container child tblLayout.Gtk.Table+TableChild
			this.paymetRequestFormFrame = new global::Gtk.Frame ();
			this.paymetRequestFormFrame.Name = "paymetRequestFormFrame";
			this.paymetRequestFormFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child paymetRequestFormFrame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtPaymentForm = new global::Gtk.TextView ();
			this.txtPaymentForm.CanFocus = true;
			this.txtPaymentForm.Name = "txtPaymentForm";
			this.GtkScrolledWindow.Add (this.txtPaymentForm);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.paymetRequestFormFrame.Add (this.GtkAlignment);
			this.lblPaymentRequestForm = new global::Gtk.Label ();
			this.lblPaymentRequestForm.Name = "lblPaymentRequestForm";
			this.lblPaymentRequestForm.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Payment Request Form</b>");
			this.lblPaymentRequestForm.UseMarkup = true;
			this.paymetRequestFormFrame.LabelWidget = this.lblPaymentRequestForm;
			this.tblLayout.Add (this.paymetRequestFormFrame);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblLayout [this.paymetRequestFormFrame]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			// Container child tblLayout.Gtk.Table+TableChild
			this.requestParamsFrame = new global::Gtk.Frame ();
			this.requestParamsFrame.Name = "requestParamsFrame";
			this.requestParamsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child requestParamsFrame.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.tblPaymentRequest = new global::Gtk.Table (((uint)(8)), ((uint)(4)), false);
			this.tblPaymentRequest.Name = "tblPaymentRequest";
			this.tblPaymentRequest.RowSpacing = ((uint)(6));
			this.tblPaymentRequest.ColumnSpacing = ((uint)(6));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.baggageFieldsVBox = new global::Gtk.VBox ();
			this.baggageFieldsVBox.Name = "baggageFieldsVBox";
			this.baggageFieldsVBox.Spacing = 6;
			// Container child baggageFieldsVBox.Gtk.Box+BoxChild
			this.lblBaggageFields = new global::Gtk.Label ();
			this.lblBaggageFields.Name = "lblBaggageFields";
			this.lblBaggageFields.Xalign = 1F;
			this.lblBaggageFields.LabelProp = global::Mono.Unix.Catalog.GetString ("Baggage Fields:");
			this.baggageFieldsVBox.Add (this.lblBaggageFields);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.baggageFieldsVBox [this.lblBaggageFields]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			this.tblPaymentRequest.Add (this.baggageFieldsVBox);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.baggageFieldsVBox]));
			w6.TopAttach = ((uint)(6));
			w6.BottomAttach = ((uint)(7));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.cmbCurrency = global::Gtk.ComboBox.NewText ();
			this.cmbCurrency.Name = "cmbCurrency";
			this.tblPaymentRequest.Add (this.cmbCurrency);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.cmbCurrency]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.commentsVBox = new global::Gtk.VBox ();
			this.commentsVBox.Name = "commentsVBox";
			this.commentsVBox.Spacing = 6;
			// Container child commentsVBox.Gtk.Box+BoxChild
			this.lblComments = new global::Gtk.Label ();
			this.lblComments.Name = "lblComments";
			this.lblComments.Xalign = 1F;
			this.lblComments.LabelProp = global::Mono.Unix.Catalog.GetString ("Comments:");
			this.commentsVBox.Add (this.lblComments);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.commentsVBox [this.lblComments]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.tblPaymentRequest.Add (this.commentsVBox);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.commentsVBox]));
			w9.TopAttach = ((uint)(6));
			w9.BottomAttach = ((uint)(7));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.failUrlMethodHBox = new global::Gtk.HBox ();
			this.failUrlMethodHBox.Name = "failUrlMethodHBox";
			this.failUrlMethodHBox.Spacing = 6;
			// Container child failUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtFailGetMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("GET"));
			this.rbtFailGetMethod.CanFocus = true;
			this.rbtFailGetMethod.Name = "rbtFailGetMethod";
			this.rbtFailGetMethod.DrawIndicator = true;
			this.rbtFailGetMethod.UseUnderline = true;
			this.rbtFailGetMethod.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.failUrlMethodHBox.Add (this.rbtFailGetMethod);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.failUrlMethodHBox [this.rbtFailGetMethod]));
			w10.Position = 0;
			// Container child failUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtFailPostMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("POST"));
			this.rbtFailPostMethod.CanFocus = true;
			this.rbtFailPostMethod.Name = "rbtFailPostMethod";
			this.rbtFailPostMethod.DrawIndicator = true;
			this.rbtFailPostMethod.UseUnderline = true;
			this.rbtFailPostMethod.Group = this.rbtFailGetMethod.Group;
			this.failUrlMethodHBox.Add (this.rbtFailPostMethod);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.failUrlMethodHBox [this.rbtFailPostMethod]));
			w11.Position = 1;
			// Container child failUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtFailLinkMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("LINK"));
			this.rbtFailLinkMethod.CanFocus = true;
			this.rbtFailLinkMethod.Name = "rbtFailLinkMethod";
			this.rbtFailLinkMethod.DrawIndicator = true;
			this.rbtFailLinkMethod.UseUnderline = true;
			this.rbtFailLinkMethod.Group = this.rbtFailGetMethod.Group;
			this.failUrlMethodHBox.Add (this.rbtFailLinkMethod);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.failUrlMethodHBox [this.rbtFailLinkMethod]));
			w12.Position = 2;
			this.tblPaymentRequest.Add (this.failUrlMethodHBox);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.failUrlMethodHBox]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtComments = new global::Gtk.TextView ();
			this.txtComments.CanFocus = true;
			this.txtComments.Name = "txtComments";
			this.GtkScrolledWindow1.Add (this.txtComments);
			this.tblPaymentRequest.Add (this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.GtkScrolledWindow1]));
			w15.TopAttach = ((uint)(6));
			w15.BottomAttach = ((uint)(7));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.txtBaggageFields = new global::Gtk.TextView ();
			this.txtBaggageFields.CanFocus = true;
			this.txtBaggageFields.Name = "txtBaggageFields";
			this.GtkScrolledWindow2.Add (this.txtBaggageFields);
			this.tblPaymentRequest.Add (this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.GtkScrolledWindow2]));
			w17.TopAttach = ((uint)(6));
			w17.BottomAttach = ((uint)(7));
			w17.LeftAttach = ((uint)(3));
			w17.RightAttach = ((uint)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblAccount = new global::Gtk.Label ();
			this.lblAccount.Name = "lblAccount";
			this.lblAccount.Xalign = 1F;
			this.lblAccount.LabelProp = global::Mono.Unix.Catalog.GetString ("Merchant's Account:");
			this.tblPaymentRequest.Add (this.lblAccount);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblAccount]));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblAmount = new global::Gtk.Label ();
			this.lblAmount.Name = "lblAmount";
			this.lblAmount.Xalign = 1F;
			this.lblAmount.LabelProp = global::Mono.Unix.Catalog.GetString ("Amount:");
			this.tblPaymentRequest.Add (this.lblAmount);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblAmount]));
			w19.TopAttach = ((uint)(3));
			w19.BottomAttach = ((uint)(4));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblBuyerAccount = new global::Gtk.Label ();
			this.lblBuyerAccount.Name = "lblBuyerAccount";
			this.lblBuyerAccount.Xalign = 1F;
			this.lblBuyerAccount.LabelProp = global::Mono.Unix.Catalog.GetString ("Buyer's Account:");
			this.tblPaymentRequest.Add (this.lblBuyerAccount);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblBuyerAccount]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblCurrency = new global::Gtk.Label ();
			this.lblCurrency.Name = "lblCurrency";
			this.lblCurrency.Xalign = 1F;
			this.lblCurrency.LabelProp = global::Mono.Unix.Catalog.GetString ("Currency:");
			this.tblPaymentRequest.Add (this.lblCurrency);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblCurrency]));
			w21.TopAttach = ((uint)(4));
			w21.BottomAttach = ((uint)(5));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblFailUrl = new global::Gtk.Label ();
			this.lblFailUrl.Name = "lblFailUrl";
			this.lblFailUrl.Xalign = 1F;
			this.lblFailUrl.LabelProp = global::Mono.Unix.Catalog.GetString ("Fail URL:");
			this.tblPaymentRequest.Add (this.lblFailUrl);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblFailUrl]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblFailUrlMethod = new global::Gtk.Label ();
			this.lblFailUrlMethod.Name = "lblFailUrlMethod";
			this.lblFailUrlMethod.Xalign = 1F;
			this.lblFailUrlMethod.LabelProp = global::Mono.Unix.Catalog.GetString ("Fail URL Method:");
			this.tblPaymentRequest.Add (this.lblFailUrlMethod);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblFailUrlMethod]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblMerchantRef = new global::Gtk.Label ();
			this.lblMerchantRef.Name = "lblMerchantRef";
			this.lblMerchantRef.Xalign = 1F;
			this.lblMerchantRef.LabelProp = global::Mono.Unix.Catalog.GetString ("Merchant Ref:");
			this.tblPaymentRequest.Add (this.lblMerchantRef);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblMerchantRef]));
			w24.TopAttach = ((uint)(5));
			w24.BottomAttach = ((uint)(6));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblStatusUrl = new global::Gtk.Label ();
			this.lblStatusUrl.Name = "lblStatusUrl";
			this.lblStatusUrl.Xalign = 1F;
			this.lblStatusUrl.LabelProp = global::Mono.Unix.Catalog.GetString ("Status URL:");
			this.tblPaymentRequest.Add (this.lblStatusUrl);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblStatusUrl]));
			w25.TopAttach = ((uint)(4));
			w25.BottomAttach = ((uint)(5));
			w25.LeftAttach = ((uint)(2));
			w25.RightAttach = ((uint)(3));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblStatusUrlMethod = new global::Gtk.Label ();
			this.lblStatusUrlMethod.Name = "lblStatusUrlMethod";
			this.lblStatusUrlMethod.Xalign = 1F;
			this.lblStatusUrlMethod.LabelProp = global::Mono.Unix.Catalog.GetString ("Status URL Method:");
			this.tblPaymentRequest.Add (this.lblStatusUrlMethod);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblStatusUrlMethod]));
			w26.TopAttach = ((uint)(5));
			w26.BottomAttach = ((uint)(6));
			w26.LeftAttach = ((uint)(2));
			w26.RightAttach = ((uint)(3));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblStore = new global::Gtk.Label ();
			this.lblStore.Name = "lblStore";
			this.lblStore.Xalign = 1F;
			this.lblStore.LabelProp = global::Mono.Unix.Catalog.GetString ("Store:");
			this.tblPaymentRequest.Add (this.lblStore);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblStore]));
			w27.TopAttach = ((uint)(2));
			w27.BottomAttach = ((uint)(3));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblSuccessUrl = new global::Gtk.Label ();
			this.lblSuccessUrl.Name = "lblSuccessUrl";
			this.lblSuccessUrl.Xalign = 1F;
			this.lblSuccessUrl.LabelProp = global::Mono.Unix.Catalog.GetString ("Success URL:");
			this.tblPaymentRequest.Add (this.lblSuccessUrl);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblSuccessUrl]));
			w28.LeftAttach = ((uint)(2));
			w28.RightAttach = ((uint)(3));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.lblSuccessUrlMethod = new global::Gtk.Label ();
			this.lblSuccessUrlMethod.Name = "lblSuccessUrlMethod";
			this.lblSuccessUrlMethod.Xalign = 1F;
			this.lblSuccessUrlMethod.LabelProp = global::Mono.Unix.Catalog.GetString ("Success URL Method:");
			this.tblPaymentRequest.Add (this.lblSuccessUrlMethod);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.lblSuccessUrlMethod]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.LeftAttach = ((uint)(2));
			w29.RightAttach = ((uint)(3));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.requestButtons = new global::Gtk.HButtonBox ();
			this.requestButtons.Name = "requestButtons";
			this.requestButtons.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child requestButtons.Gtk.ButtonBox+ButtonBoxChild
			this.btnGenerate = new global::Gtk.Button ();
			this.btnGenerate.CanFocus = true;
			this.btnGenerate.Name = "btnGenerate";
			this.btnGenerate.UseUnderline = true;
			this.btnGenerate.Label = global::Mono.Unix.Catalog.GetString ("Generate");
			this.requestButtons.Add (this.btnGenerate);
			global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.requestButtons [this.btnGenerate]));
			w30.Expand = false;
			w30.Fill = false;
			this.tblPaymentRequest.Add (this.requestButtons);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.requestButtons]));
			w31.TopAttach = ((uint)(7));
			w31.BottomAttach = ((uint)(8));
			w31.LeftAttach = ((uint)(3));
			w31.RightAttach = ((uint)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.statusUrlMethodHBox = new global::Gtk.HBox ();
			this.statusUrlMethodHBox.Name = "statusUrlMethodHBox";
			this.statusUrlMethodHBox.Spacing = 6;
			// Container child statusUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtStatusGetMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("GET"));
			this.rbtStatusGetMethod.CanFocus = true;
			this.rbtStatusGetMethod.Name = "rbtStatusGetMethod";
			this.rbtStatusGetMethod.DrawIndicator = true;
			this.rbtStatusGetMethod.UseUnderline = true;
			this.rbtStatusGetMethod.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.statusUrlMethodHBox.Add (this.rbtStatusGetMethod);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.statusUrlMethodHBox [this.rbtStatusGetMethod]));
			w32.Position = 0;
			// Container child statusUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtStatusPostMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("POST"));
			this.rbtStatusPostMethod.CanFocus = true;
			this.rbtStatusPostMethod.Name = "rbtStatusPostMethod";
			this.rbtStatusPostMethod.DrawIndicator = true;
			this.rbtStatusPostMethod.UseUnderline = true;
			this.rbtStatusPostMethod.Group = this.rbtStatusGetMethod.Group;
			this.statusUrlMethodHBox.Add (this.rbtStatusPostMethod);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.statusUrlMethodHBox [this.rbtStatusPostMethod]));
			w33.Position = 1;
			// Container child statusUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtStatusLinkMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("LINK"));
			this.rbtStatusLinkMethod.CanFocus = true;
			this.rbtStatusLinkMethod.Name = "rbtStatusLinkMethod";
			this.rbtStatusLinkMethod.DrawIndicator = true;
			this.rbtStatusLinkMethod.UseUnderline = true;
			this.rbtStatusLinkMethod.Group = this.rbtStatusGetMethod.Group;
			this.statusUrlMethodHBox.Add (this.rbtStatusLinkMethod);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.statusUrlMethodHBox [this.rbtStatusLinkMethod]));
			w34.Position = 2;
			this.tblPaymentRequest.Add (this.statusUrlMethodHBox);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.statusUrlMethodHBox]));
			w35.TopAttach = ((uint)(5));
			w35.BottomAttach = ((uint)(6));
			w35.LeftAttach = ((uint)(3));
			w35.RightAttach = ((uint)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.successUrlMethodHBox = new global::Gtk.HBox ();
			this.successUrlMethodHBox.Name = "successUrlMethodHBox";
			this.successUrlMethodHBox.Spacing = 6;
			// Container child successUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtSuccessGetMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("GET"));
			this.rbtSuccessGetMethod.CanFocus = true;
			this.rbtSuccessGetMethod.Name = "rbtSuccessGetMethod";
			this.rbtSuccessGetMethod.DrawIndicator = true;
			this.rbtSuccessGetMethod.UseUnderline = true;
			this.rbtSuccessGetMethod.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.successUrlMethodHBox.Add (this.rbtSuccessGetMethod);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.successUrlMethodHBox [this.rbtSuccessGetMethod]));
			w36.Position = 0;
			// Container child successUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtSuccessPostMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("POST"));
			this.rbtSuccessPostMethod.CanFocus = true;
			this.rbtSuccessPostMethod.Name = "rbtSuccessPostMethod";
			this.rbtSuccessPostMethod.DrawIndicator = true;
			this.rbtSuccessPostMethod.UseUnderline = true;
			this.rbtSuccessPostMethod.Group = this.rbtSuccessGetMethod.Group;
			this.successUrlMethodHBox.Add (this.rbtSuccessPostMethod);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.successUrlMethodHBox [this.rbtSuccessPostMethod]));
			w37.Position = 1;
			// Container child successUrlMethodHBox.Gtk.Box+BoxChild
			this.rbtSuccessLinkMethod = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("LINK"));
			this.rbtSuccessLinkMethod.CanFocus = true;
			this.rbtSuccessLinkMethod.Name = "rbtSuccessLinkMethod";
			this.rbtSuccessLinkMethod.DrawIndicator = true;
			this.rbtSuccessLinkMethod.UseUnderline = true;
			this.rbtSuccessLinkMethod.Group = this.rbtSuccessGetMethod.Group;
			this.successUrlMethodHBox.Add (this.rbtSuccessLinkMethod);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.successUrlMethodHBox [this.rbtSuccessLinkMethod]));
			w38.Position = 2;
			this.tblPaymentRequest.Add (this.successUrlMethodHBox);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.successUrlMethodHBox]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(3));
			w39.RightAttach = ((uint)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.txtAmount = new global::Gtk.SpinButton (0, 100000, 1);
			this.txtAmount.CanFocus = true;
			this.txtAmount.Name = "txtAmount";
			this.txtAmount.Adjustment.PageIncrement = 10;
			this.txtAmount.ClimbRate = 1;
			this.txtAmount.Digits = ((uint)(4));
			this.txtAmount.Numeric = true;
			this.tblPaymentRequest.Add (this.txtAmount);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.txtAmount]));
			w40.TopAttach = ((uint)(3));
			w40.BottomAttach = ((uint)(4));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.txtBuyerAccount = new global::Gtk.Entry ();
			this.txtBuyerAccount.CanFocus = true;
			this.txtBuyerAccount.Name = "txtBuyerAccount";
			this.txtBuyerAccount.IsEditable = true;
			this.txtBuyerAccount.InvisibleChar = '●';
			this.tblPaymentRequest.Add (this.txtBuyerAccount);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.txtBuyerAccount]));
			w41.TopAttach = ((uint)(1));
			w41.BottomAttach = ((uint)(2));
			w41.LeftAttach = ((uint)(1));
			w41.RightAttach = ((uint)(2));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.txtFailUrl = new global::Gtk.Entry ();
			this.txtFailUrl.CanFocus = true;
			this.txtFailUrl.Name = "txtFailUrl";
			this.txtFailUrl.IsEditable = true;
			this.txtFailUrl.InvisibleChar = '●';
			this.tblPaymentRequest.Add (this.txtFailUrl);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.txtFailUrl]));
			w42.TopAttach = ((uint)(2));
			w42.BottomAttach = ((uint)(3));
			w42.LeftAttach = ((uint)(3));
			w42.RightAttach = ((uint)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.txtMerchantAccount = new global::Gtk.Entry ();
			this.txtMerchantAccount.CanFocus = true;
			this.txtMerchantAccount.Name = "txtMerchantAccount";
			this.txtMerchantAccount.IsEditable = true;
			this.txtMerchantAccount.InvisibleChar = '●';
			this.tblPaymentRequest.Add (this.txtMerchantAccount);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.txtMerchantAccount]));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.txtMerchantRef = new global::Gtk.Entry ();
			this.txtMerchantRef.CanFocus = true;
			this.txtMerchantRef.Name = "txtMerchantRef";
			this.txtMerchantRef.IsEditable = true;
			this.txtMerchantRef.InvisibleChar = '●';
			this.tblPaymentRequest.Add (this.txtMerchantRef);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.txtMerchantRef]));
			w44.TopAttach = ((uint)(5));
			w44.BottomAttach = ((uint)(6));
			w44.LeftAttach = ((uint)(1));
			w44.RightAttach = ((uint)(2));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.txtStatusUrl = new global::Gtk.Entry ();
			this.txtStatusUrl.CanFocus = true;
			this.txtStatusUrl.Name = "txtStatusUrl";
			this.txtStatusUrl.IsEditable = true;
			this.txtStatusUrl.InvisibleChar = '●';
			this.tblPaymentRequest.Add (this.txtStatusUrl);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.txtStatusUrl]));
			w45.TopAttach = ((uint)(4));
			w45.BottomAttach = ((uint)(5));
			w45.LeftAttach = ((uint)(3));
			w45.RightAttach = ((uint)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.txtStore = new global::Gtk.Entry ();
			this.txtStore.CanFocus = true;
			this.txtStore.Name = "txtStore";
			this.txtStore.IsEditable = true;
			this.txtStore.InvisibleChar = '●';
			this.tblPaymentRequest.Add (this.txtStore);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.txtStore]));
			w46.TopAttach = ((uint)(2));
			w46.BottomAttach = ((uint)(3));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPaymentRequest.Gtk.Table+TableChild
			this.txtSuccessUrl = new global::Gtk.Entry ();
			this.txtSuccessUrl.CanFocus = true;
			this.txtSuccessUrl.Name = "txtSuccessUrl";
			this.txtSuccessUrl.IsEditable = true;
			this.txtSuccessUrl.InvisibleChar = '●';
			this.tblPaymentRequest.Add (this.txtSuccessUrl);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.tblPaymentRequest [this.txtSuccessUrl]));
			w47.LeftAttach = ((uint)(3));
			w47.RightAttach = ((uint)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.tblPaymentRequest);
			this.requestParamsFrame.Add (this.GtkAlignment1);
			this.lblRequestParams = new global::Gtk.Label ();
			this.lblRequestParams.Name = "lblRequestParams";
			this.lblRequestParams.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Payment Request Parameters</b>");
			this.lblRequestParams.UseMarkup = true;
			this.requestParamsFrame.LabelWidget = this.lblRequestParams;
			this.tblLayout.Add (this.requestParamsFrame);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.tblLayout [this.requestParamsFrame]));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.tblLayout);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnGenerate.Clicked += new global::System.EventHandler (this.OnGenerateFormClicked);
		}
	}
}
