
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox layoutVBox;
	private global::Gtk.Frame apiCredentialsFrame;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.Table tblApiCredentials;
	private global::Gtk.Label lblAccountNumber;
	private global::Gtk.Label lblApiName;
	private global::Gtk.Label lblSecurityWord;
	private global::Gtk.Entry txtAccount;
	private global::Gtk.Entry txtApiName;
	private global::Gtk.Entry txtSecurityWord;
	private global::Gtk.Label lblApiCredentials;
	private global::Gtk.Notebook operationsNotebook;
	private global::LRDemo.BalanceWidget balanceWidget;
	private global::Gtk.Label lblBalanceTab;
	private global::LRDemo.AccountWidget accountWidget;
	private global::Gtk.Label lblAccountNameTab;
	private global::LRDemo.TransferWidget transferWidget;
	private global::Gtk.Label lblTransfer;
	private global::LRDemo.HistoryWidget historyWidget;
	private global::Gtk.Label lblHistory1;
	private global::LRDemo.SCIPaymentRequestWidget sciPaymentRequestWidget;
	private global::Gtk.Label lblPaymentRequest;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Liberty Reserve");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.layoutVBox = new global::Gtk.VBox ();
		this.layoutVBox.Name = "layoutVBox";
		this.layoutVBox.Spacing = 6;
		// Container child layoutVBox.Gtk.Box+BoxChild
		this.apiCredentialsFrame = new global::Gtk.Frame ();
		this.apiCredentialsFrame.Name = "apiCredentialsFrame";
		this.apiCredentialsFrame.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child apiCredentialsFrame.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.tblApiCredentials = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.tblApiCredentials.Name = "tblApiCredentials";
		this.tblApiCredentials.RowSpacing = ((uint)(6));
		this.tblApiCredentials.ColumnSpacing = ((uint)(6));
		// Container child tblApiCredentials.Gtk.Table+TableChild
		this.lblAccountNumber = new global::Gtk.Label ();
		this.lblAccountNumber.Name = "lblAccountNumber";
		this.lblAccountNumber.Xalign = 1F;
		this.lblAccountNumber.LabelProp = global::Mono.Unix.Catalog.GetString ("Account Number:");
		this.tblApiCredentials.Add (this.lblAccountNumber);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tblApiCredentials [this.lblAccountNumber]));
		w1.YPadding = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblApiCredentials.Gtk.Table+TableChild
		this.lblApiName = new global::Gtk.Label ();
		this.lblApiName.Name = "lblApiName";
		this.lblApiName.Xalign = 1F;
		this.lblApiName.LabelProp = global::Mono.Unix.Catalog.GetString ("API Name:");
		this.tblApiCredentials.Add (this.lblApiName);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblApiCredentials [this.lblApiName]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblApiCredentials.Gtk.Table+TableChild
		this.lblSecurityWord = new global::Gtk.Label ();
		this.lblSecurityWord.Name = "lblSecurityWord";
		this.lblSecurityWord.Xalign = 1F;
		this.lblSecurityWord.LabelProp = global::Mono.Unix.Catalog.GetString ("Security Word:");
		this.tblApiCredentials.Add (this.lblSecurityWord);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblApiCredentials [this.lblSecurityWord]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblApiCredentials.Gtk.Table+TableChild
		this.txtAccount = new global::Gtk.Entry ();
		this.txtAccount.CanFocus = true;
		this.txtAccount.Name = "txtAccount";
		this.txtAccount.IsEditable = true;
		this.txtAccount.InvisibleChar = '●';
		this.tblApiCredentials.Add (this.txtAccount);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblApiCredentials [this.txtAccount]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YPadding = ((uint)(3));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblApiCredentials.Gtk.Table+TableChild
		this.txtApiName = new global::Gtk.Entry ();
		this.txtApiName.CanFocus = true;
		this.txtApiName.Name = "txtApiName";
		this.txtApiName.IsEditable = true;
		this.txtApiName.InvisibleChar = '●';
		this.tblApiCredentials.Add (this.txtApiName);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblApiCredentials [this.txtApiName]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblApiCredentials.Gtk.Table+TableChild
		this.txtSecurityWord = new global::Gtk.Entry ();
		this.txtSecurityWord.CanFocus = true;
		this.txtSecurityWord.Name = "txtSecurityWord";
		this.txtSecurityWord.IsEditable = true;
		this.txtSecurityWord.Visibility = false;
		this.txtSecurityWord.InvisibleChar = '●';
		this.tblApiCredentials.Add (this.txtSecurityWord);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblApiCredentials [this.txtSecurityWord]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.tblApiCredentials);
		this.apiCredentialsFrame.Add (this.GtkAlignment);
		this.lblApiCredentials = new global::Gtk.Label ();
		this.lblApiCredentials.Name = "lblApiCredentials";
		this.lblApiCredentials.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>API Credentials</b>");
		this.lblApiCredentials.UseMarkup = true;
		this.apiCredentialsFrame.LabelWidget = this.lblApiCredentials;
		this.layoutVBox.Add (this.apiCredentialsFrame);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.layoutVBox [this.apiCredentialsFrame]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(3));
		// Container child layoutVBox.Gtk.Box+BoxChild
		this.operationsNotebook = new global::Gtk.Notebook ();
		this.operationsNotebook.CanFocus = true;
		this.operationsNotebook.Name = "operationsNotebook";
		this.operationsNotebook.CurrentPage = 4;
		// Container child operationsNotebook.Gtk.Notebook+NotebookChild
		this.balanceWidget = new global::LRDemo.BalanceWidget ();
		this.balanceWidget.Events = ((global::Gdk.EventMask)(256));
		this.balanceWidget.Name = "balanceWidget";
		this.operationsNotebook.Add (this.balanceWidget);
		// Notebook tab
		this.lblBalanceTab = new global::Gtk.Label ();
		this.lblBalanceTab.Name = "lblBalanceTab";
		this.lblBalanceTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Balance");
		this.operationsNotebook.SetTabLabel (this.balanceWidget, this.lblBalanceTab);
		this.lblBalanceTab.ShowAll ();
		// Container child operationsNotebook.Gtk.Notebook+NotebookChild
		this.accountWidget = new global::LRDemo.AccountWidget ();
		this.accountWidget.Events = ((global::Gdk.EventMask)(256));
		this.accountWidget.Name = "accountWidget";
		this.operationsNotebook.Add (this.accountWidget);
		global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.operationsNotebook [this.accountWidget]));
		w11.Position = 1;
		// Notebook tab
		this.lblAccountNameTab = new global::Gtk.Label ();
		this.lblAccountNameTab.Name = "lblAccountNameTab";
		this.lblAccountNameTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Account Name");
		this.operationsNotebook.SetTabLabel (this.accountWidget, this.lblAccountNameTab);
		this.lblAccountNameTab.ShowAll ();
		// Container child operationsNotebook.Gtk.Notebook+NotebookChild
		this.transferWidget = new global::LRDemo.TransferWidget ();
		this.transferWidget.Events = ((global::Gdk.EventMask)(256));
		this.transferWidget.Name = "transferWidget";
		this.operationsNotebook.Add (this.transferWidget);
		global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.operationsNotebook [this.transferWidget]));
		w12.Position = 2;
		// Notebook tab
		this.lblTransfer = new global::Gtk.Label ();
		this.lblTransfer.Name = "lblTransfer";
		this.lblTransfer.LabelProp = global::Mono.Unix.Catalog.GetString ("Transfer");
		this.operationsNotebook.SetTabLabel (this.transferWidget, this.lblTransfer);
		this.lblTransfer.ShowAll ();
		// Container child operationsNotebook.Gtk.Notebook+NotebookChild
		this.historyWidget = new global::LRDemo.HistoryWidget ();
		this.historyWidget.Events = ((global::Gdk.EventMask)(256));
		this.historyWidget.Name = "historyWidget";
		this.operationsNotebook.Add (this.historyWidget);
		global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.operationsNotebook [this.historyWidget]));
		w13.Position = 3;
		// Notebook tab
		this.lblHistory1 = new global::Gtk.Label ();
		this.lblHistory1.Name = "lblHistory1";
		this.lblHistory1.LabelProp = global::Mono.Unix.Catalog.GetString ("History");
		this.operationsNotebook.SetTabLabel (this.historyWidget, this.lblHistory1);
		this.lblHistory1.ShowAll ();
		// Container child operationsNotebook.Gtk.Notebook+NotebookChild
		this.sciPaymentRequestWidget = new global::LRDemo.SCIPaymentRequestWidget ();
		this.sciPaymentRequestWidget.Events = ((global::Gdk.EventMask)(256));
		this.sciPaymentRequestWidget.Name = "sciPaymentRequestWidget";
		this.operationsNotebook.Add (this.sciPaymentRequestWidget);
		global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.operationsNotebook [this.sciPaymentRequestWidget]));
		w14.Position = 4;
		// Notebook tab
		this.lblPaymentRequest = new global::Gtk.Label ();
		this.lblPaymentRequest.Name = "lblPaymentRequest";
		this.lblPaymentRequest.LabelProp = global::Mono.Unix.Catalog.GetString ("Payment Request");
		this.operationsNotebook.SetTabLabel (this.sciPaymentRequestWidget, this.lblPaymentRequest);
		this.lblPaymentRequest.ShowAll ();
		this.layoutVBox.Add (this.operationsNotebook);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.layoutVBox [this.operationsNotebook]));
		w15.Position = 1;
		this.Add (this.layoutVBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 608;
		this.DefaultHeight = 550;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
